### ISSUE TITLE
Liveview FIX for Sony Alpha Cameras

### ISSUE THREAD

**Issue by v4mp1** [indilib/indi#1034]
https://indilib.org/forum/ccds-dslrs/5881-sony-alpha-5100-viewfinder-widget-error-fixed.html

**Comment by knro** [comment]
Thank you for the fix. Is this applicable to all Sony cameras?

**Comment by v4mp1** [comment]
I have only the 5100 but my guess is it works for the whole Sony DSLM android based firmware lineup.

**Comment by knro** [comment]
Ok I applied this to master, can you test and verify?

**Comment by v4mp1** [comment]
I don't see any changes there? https://github.com/indilib/indi-3rdparty/tree/master/indi-gphoto

**Comment by knro** [comment]
You're right, I pushed it to the gphoto_autoexposure branch by mistake. Can you test it there?

**Comment by v4mp1** [comment]
Alright, I can test it in some hours. Thanks.

**Comment by v4mp1** [comment]
Jasem it works but you forgot to add Sony in the stop preview section.
I have to click twice on the X to close the preview window:

int gphoto_stop_preview(gphoto_driver *gphoto)
{
    // Olympus cameras support streaming but without viewfinder_widget
    if (strcasestr(gphoto->manufacturer, "OLYMPUS"))
        return GP_OK;

**Comment by v4mp1** [comment]
Everything works now Jasem you can upload to master.

Thanks.
