### ISSUE TITLE
SONY DSLR A55 error in indi_sony_ccd

### ISSUE THREAD

**Issue by philpugh51** [indilib/indi#710]
I apologise if this is the wrong place to report this issue....

using latest (nightly build) of indilib etc I get an error when connecting my SONY DSLR/SLT A55 .  I have attached a verbose log that gives the full description.  I have set the camera to BULB exposure
[log_16-35-50.txt](https://github.com/indilib/indi/files/2376908/log_16-35-50.txt)

**Comment by knro** [comment]
Please check if you still can replicate this issue on Nightly. IIRC, this was fixed a while ago.

**Comment by philpugh51** [comment]
Ok - dowloaded nightly build and I can now connect to my SLT-A55 - this is better!
However I still cannot initiate an exposure - is this to be expected?  I am using it with latest KSTARS/INDIlib and get the following error as in the atyteched log file (which I edited to truncate it)

Cheers

Phil
[Log SLTA55.txt](https://github.com/indilib/indi/files/2522159/Log.SLTA55.txt)

**Comment by philpugh51** [comment]
Sorry - forgot to mention that in the control panel there is nothing in the Shutter Release setting in the INDI control panel setting for the camera  I manually set the pixel info etc before trying an exposure

**Comment by knro** [comment]
The log is not detailed enough. Edit your profile and uncheck auto connect, then after you start the driver, go the "options" tab of the driver and make sure that all debug checkboxes are checked, then go to main control panel and connect. It should now log everything.

**Comment by philpugh51** [comment]
Attached is new log with more debug info.

Phil
[log_17-06-00.txt](https://github.com/indilib/indi/files/2522995/log_17-06-00.txt)

**Comment by philpugh51** [comment]
BTW the A55 is definitely in BULB mode!

**Comment by knro** [comment]
Still same issue with latest drivers and libgphoto2?

**Comment by philpugh51** [comment]
will download and try later this week

THanks

Phil

**Comment by knro** [comment]
Ok one last thing to try. Try to use the INDI Gphoto driver and not Sony DSLR.. does it make any difference?

**Comment by philpugh51** [comment]
Tried with Gphoto CCD driver - very similar results - see attached log.
Phil
[log_11-16-45.txt](https://github.com/indilib/indi/files/3620700/log_11-16-45.txt)

**Comment by philpugh51** [comment]
Is there anything I can do to debug the connection?  Is the A55 not responding as it should?

Phil

**Comment by knro** [comment]
Thanks for the report. Please open this issue in the 3rdparty repo issues --> https://github.com/indilib/indi-3rdparty/issues
